apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  labels:
    app: mongo-express
    type: frontend
spec:
  containers:
  - name: mongo-express
    image: mongo-express:latest
    ports:
    - containerPort: 8081
#    resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
    env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      valueFrom:
        secretKeyRef:
          key: mongo-root-username  
          name: mongodb-secret
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      valueFrom:
        secretKeyRef:
          key: mongo-root-password
          name: mongodb-secret
    - name: ME_CONFIG_MONGODB_SERVER
      valueFrom:
        configMapKeyRef:
          key: database_url
          name: mongodbconfigmap
