apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
    type: backend
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    ports:
    - containerPort: 27017
  # resources:
  #   limits:  
  #     memory: "128Mi"
  #     cpu: "500m"
    env: 
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
       secretKeyRef:
        name: mongodb-secret
        key: mongo-root-username  
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
       secretKeyRef:
        name: mongodb-secret
        key: mongo-root-password
           
