apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: "http-server"
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-pv-storage
      volumes:
      - name: nginx-pv-storage
        persistentVolumeClaim:
          claimName: nginx-pv-claim


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: frontend
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000

